### ISSUE TITLE
Homey 5.0 Accu level missing

### ISSUE THREAD

**Issue by gerenher** [ricott/homey-com.volvocars#10]
Since upgrade to Homey 5.0 the flow card Accu level is missing.

**Comment by gerenher** [comment]
![Screenshot_20210216-101038_Homey](https://user-images.githubusercontent.com/79138011/108041738-40f54b00-703f-11eb-8941-2a3dfade1518.jpg)

**Comment by ricott** [comment]
For the battery, I use the built-in capability in Homey called `measure_battery`. I don't maintain any trigger, condition or action related to it. 

I quickly checked and see there is a trigger for battery level changed - is that the one you are missing (I have it)?
Also checking the documentation here, http://developer.athom.com/docs/apps-reference, check the top table for measure_battery and click `...` on the far right. It will list the properties and flows for this capability. The definition of a trigger is there, "The battery level changed".

It might be worth testing a restart of your Homey if you have not done that after the v5 upgrade.

**Comment by ricott** [comment]
I guess this problem was solved? Might have been that Athom renamed the condition in v5.
Reopen if not solved.
