### ISSUE TITLE
Unable to add/connect to Volvo

### ISSUE THREAD

**Issue by S90BC** [ricott/homey-com.volvocars#13]
Hi, when i try to connect my Volvo to Homey it fails. After filling out my credentials i get the message  'No new devices found' (in my case in Dutch)
What am i doing wrong?
Regards,
Bart

**Comment by S90BC** [comment]
Ok..I don't know what went wrong but i deinstalled the app en reinstalled it again AND restarted Homey And then it found the car right away...

**Comment by ricott** [comment]
Great that is solved itself :)
I know there have been some problems in the past with passwords containing some special characters. I couldn't reproduce that problem myself but others could. May depend on your Homey firmware version.

**Comment by S90BC** [comment]
Yes maybe firmware, i am beta testing 6.0.0-rc.5
I didn' t change the password...maybe a homey restart was enough...but i reinstalled the app and restarted homey...so i am still jot sure what the issue was :(
