### ISSUE TITLE
Adding app gives no devices found

### ISSUE THREAD

**Issue by rdoelen** [ricott/homey-com.volvocars#15]
I trying to add the Volvo on Call app. But it gives no devices found error. I changed the password to get rid of the special characters. Till now no result.

I have a xc-40 2022 jan version

**Comment by ricott** [comment]
Hi!

Unfortunately, there is a problem with the 2022 model year cars.

Below is copied from the forum thread where I replied to a user asking a similar question
*******
I just got a new XC60 hybrid myself after a few years without a Volvo car.
Don’t know how new your car is, mine is the model year 2022. Volvo has changed something in their APIs and these new cars are not available here. I also can’t add my car to Tibber’s app, when contacting their support they said the car is “too new” and they are talking to Volvo about how to solve this but don’t expect a solution in a near future.

Even the “new” [Connected Vehicle API](https://developer.volvocars.com/volvo-api/connected-vehicle/#overview) from Volvo says

>This API works for all connected cars up to model year 2021, excluding the XC40 Recharge BEV.

The [Extended Vehicle API](https://developer.volvocars.com/volvo-api/extended-vehicle/) potentially works for these model year 2022 cars, but it doesn’t support invoking commands.

If anyone has any intel on what we can use please let me know

**Comment by rdoelen** [comment]
Hi Ricot,

i have a 2022 model Volvo. It has a Google car based entertainment set. I will check if the api is updated by Volvo. I am using Volvo cars app to manage the charging. Would be great to manage it via Homey when the solar cells are generating power or use lower tariff during the night .

**Comment by ricott** [comment]
https://community.homey.app/t/app-pro-volvo-on-call/20828/98?u=richard_b
