### ISSUE TITLE
XC 40 pure Electric

### ISSUE THREAD

**Issue by Ornbo** [ricott/homey-com.volvocars#16]
Hi 

it seems to be a great app - but I cant use it for my XC40 Pure Electric and it prop the car where the app gives most sense. 

Can you please extend with this car ?

**Comment by ricott** [comment]
Hi!

Unfortunately, I am not aware of any API that allows connecting to XC40 Pure Electric, or to the model year 2022 or any other Volvo car. I wrote a little more about it here; https://community.homey.app/t/app-pro-volvo-on-call/20828/69

**Comment by Ornbo** [comment]
Thanks for you comment - hope they will open API
