### ISSUE TITLE
Can˚t connect XC60 Recharge 2021

### ISSUE THREAD

**Issue by MPinguu** [ricott/homey-com.volvocars#17]
Hi,
I have an XC60 early 2021 that fails to connect. When I add, log in and choose Device, only a blank page with the Continue button will appear. I have tested uninstalling the app and restarted Homey but the same thing happens every time. 

What do I do wrong?

Regards
Marcus

**Comment by miszterx** [comment]
Hi,

I have just did the same right now. I have a XC40. However I have also got just empty page to select the device after successful login.
![IMG_7384](https://user-images.githubusercontent.com/56317037/176270835-6f0c778b-9cfa-4f11-a7b7-00c96457a0d0.PNG)

I have tried to change to region in the app settings. Europe (my region) did what I have attached, however if I choose North America it shows the line "There is available device". Looks like in Europe it recognize my car, just cannot draw it. :( Should be a bug. I hope it will be fixed soon.

**Comment by sveeniee** [comment]
Hi 

I have the same issue with a V60 Early 2019

**Comment by ricott** [comment]
There is a test version 1.1.5 which should solve the problem.

**Comment by MPinguu** [comment]
Hi!

Now it works like a charm!

Thanks for a great app and brilliant work!

Best regards

Marcus Andersson

Från: Richard Barkestam ***@***.***>
Svara till: "ricott/homey-com.volvocars" ***@***.***>
Datum: måndag 4 juli 2022 13:55
Till: "ricott/homey-com.volvocars" ***@***.***>
Kopia: Marcus Andersson ***@***.***>, Author ***@***.***>
Ämne: Re: [ricott/homey-com.volvocars] Can˚t connect XC60 Recharge 2021 (Issue #17)


There is a test version 1.1.5 which should solve the problem.
