### ISSUE TITLE
Does not show up in Devices or in Flow

### ISSUE THREAD

**Issue by Martin840710** [ricott/homey-com.volvocars#18]
Hi!

I was reinstalling the app because I saw that the new version would support “Stop charging” but after reinstalling it does not show up in Devices or in Flow. 
I have restarted Homey and done the reinstallation several times but still not shows up. The app is visible amongs the other apps. 

Is there any update done that makes my Homey (early 2018) incompatible?

Thanks in advance. 

Best regards Martin

**Comment by ricott** [comment]
Hi!

I'm guessing this problem is solved by now, if not please reopen or create a new ticket.

**Comment by Martin840710** [comment]
Hi Richard,

Yes, I found it but I never got the Homey app to work with my Volvo V60
Recharge, early 21.
Guess it has to do how often the Volvo updates the status?

Best regards Martin


tis 6 feb. 2024 kl. 09:00 skrev Richard Barkestam ***@***.***

**Comment by ricott** [comment]
Not sure what you mean with
> Guess it has to do how often the Volvo updates the status

But you are right that certain functionality is heavily impacted by the refresh frequency from the car to the Volvo cloud, since the Homey app only talks to the Volvo cloud and not the car directly.
