### ISSUE TITLE
Triggers... no action

### ISSUE THREAD

**Issue by maheldt** [ricott/homey-com.volvocars#2]
Hi guys

Just a question. I`m trying to use the Volvo On Call app with my Homey.
Adding the triggers, conditions and actions, but nothing happens... Info regarding the
car is working within the app. 

It may be that I`m creating my flows in a wrong way, but could someone give me a hint, or send an example?

BR
Marius

**Comment by ricott** [comment]
Hi Marius,

I don't know what triggers you tested, but one main thing you need to be aware of is that the Volvo On Call (VOC) API is based on pulling data from your Homey, it is not push based. The frequency of refreshing the current state of your vehicle is decided by the Refresh status setting. Default value as of latest release is 10 minutes. This means for instance if you want to test the "a door open" trigger a door have to be open at the time the status is refreshed on your car. This can happen at maximum 10 minutes after the door was actually open, depending on how frequently the status is refreshed from your car as defined by the setting. You can set the refresh setting as low as every minute, but please be aware that this will affect the battery on your car if you don't drive it longer distances every day. VOC seems to consume a bit of battery power on the vehicle.

Regards,
Richard

**Comment by maheldt** [comment]
Hi Richard.

Thx for feedback. Im aware of the pull and refresh time. But when creating a flow with and set "when car came home" in "when" and set an action in "then", nothing happens..

Could you send me some  examples via mail? marius@heldt.no

BR
Marius

**Comment by ricott** [comment]
Assuming after email exchange that this is no longer an issue.
