### ISSUE TITLE
postVOCcommandwithposition

### ISSUE THREAD

**Issue by Roobbbiiiinnnnn** [ricott/homey-com.volvocars#20]
Hi,
I try to honk the horn and blink the light, but neither is working. I get fault code "postVOCcommandwithposition" all of the time. Heater and engine start works just fine!

**Comment by ricott** [comment]
Hi!
I'll take a look. The app is rewritten for Homey SDK 3, and I, unfortunately, don't have a car to test with myself.

**Comment by ricott** [comment]
Please give the [test version](https://homey.app/a/com.volvocars/test/) a go

**Comment by Roobbbiiiinnnnn** [comment]
Hi,
It seems to work, thank you!
I've only been able to test "blink lights" due to the time, but I will try to honk the horn tomorrow :)

/Robin


Skickat från min Galaxy



-------- Originalmeddelande --------
Från: Richard Barkestam ***@***.***>
Datum: 2022-12-21 10:39 (GMT+01:00)
Till: "ricott/homey-com.volvocars" ***@***.***>
Kopia: Roobbbiiiinnnnn ***@***.***>, Author ***@***.***>
Ämne: Re: [ricott/homey-com.volvocars] postVOCcommandwithposition (Issue #20)


Please give the test version<https://homey.app/a/com.volvocars/test/> a go

**Comment by Roobbbiiiinnnnn** [comment]
It all works now, big thanks! 🙌



Skickat från min Galaxy



-------- Originalmeddelande --------
Från: Richard Barkestam ***@***.***>
Datum: 2022-12-21 10:39 (GMT+01:00)
Till: "ricott/homey-com.volvocars" ***@***.***>
Kopia: Roobbbiiiinnnnn ***@***.***>, Author ***@***.***>
Ämne: Re: [ricott/homey-com.volvocars] postVOCcommandwithposition (Issue #20)


Please give the test version<https://homey.app/a/com.volvocars/test/> a go

**Comment by ricott** [comment]
👍
