### ISSUE TITLE
No device found

### ISSUE THREAD

**Issue by miszterx** [ricott/homey-com.volvocars#22]
Hi,
First i had a volvo xc40 2021 model. It worked properly with the homey app.

I have changed for a 2023 model for xc40.
The volco oncall app has the new car, but the homey app cannot find it if i try to add it.

Can you support this model as well? Maybe the introduced a new type for these cars?

Thanks!

**Comment by ricott** [comment]
Hi!

There is no useful official or unofficial API for these cars with Android auto.
The only API that is available is one called energy api that can show current charge level if the car is electric/hybrid. It is not possible to control anything in the car, not even start charging.
https://developer.volvocars.com/apis/energy/v1/overview/

Also, developing a pretty useless app with this energy API is a big change vs the old app. Different login using OAuth2 (which is better, but completely different than current app) and to use the official API live you need to get you app approved by Volvo.

I'm afraid this is not high on my list currently. Open for someone else implementing this.

**Comment by tjarb** [comment]
Same here, XC40 based on android using the oncall app gives no devices.
