### ISSUE TITLE
Integrating with Volvo Cars Google platform

### ISSUE THREAD

**Issue by pertomas** [ricott/homey-com.volvocars#25]
Hi,
As I understand Volvo has (now) an open API.

See - Finns massor av information att hämta: https://developer.volvocars.com/apis/#browse-apis .

Do you have any plan to do "something"? 

There thing happening in FB groups "Volvo Google (AAOS), 2022 and later" and Maxime Guillemi development for Home Assistant.

**Comment by ricott** [comment]
https://community.homey.app/t/app-pro-volvo-on-call/20828/98?u=richard_b

**Comment by pertomas** [comment]
Great job!
Now Volvo Cars can relax due to all happy Homey users again can integrate their Volvo to smart home, using Homey, Apple or Google as supporting interface phone/pad of speaking "Hi google ...".

Of course there still some bugs, Volvo Car interface is not so responsive but a sure that will improve. 

Just restarted my use of NEW Homey Volvo On Call, first function basic implemented, "Hi google, start Car-heater" and yes it's working 😃 . 

/Per Tomas
