### ISSUE TITLE
Password/User

### ISSUE THREAD

**Issue by babel91** [ricott/homey-com.volvocars#3]
Sends user and password without encryption.

**Comment by ricott** [comment]
I'd be glad to get some more details around your concern. The only protocol used by the app is https, thus all data in transit to and from the VOC API is encrypted. The Homey Volvo On Call app uses the same basic authentication that the Volvo On Call iOS/Android app use.

**Comment by babel91** [comment]
So, the issue is volvos programming? Skickat från min Samsung Galaxy-smartphone.
-------- Originalmeddelande --------Från: ricott <notifications@github.com> Datum: 2019-10-06  11:35  (GMT+01:00) Till: "ricott/homey-com.volvocars" <homey-com.volvocars@noreply.github.com> Kopia: babel91 <M.adolfsson91@gmail.com>, Author <author@noreply.github.com> Ämne: Re: [ricott/homey-com.volvocars] Password/User (#3) I'd be glad to get some more details around your concern. The only protocol used by the app is https, thus all data in transit to and from the VOC API is encrypted. The Homey Volvo On Call app uses the same basic authentication that the Volvo On Call iOS/Android app use.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ricott/homey-com.volvocars/issues/3?email_source=notifications\u0026email_token=ANM2CXKILVRS46VQ7A6HVCTQNGWPRA5CNFSM4I5ZE3E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAOFNWA#issuecomment-538728152",
"url": "https://github.com/ricott/homey-com.volvocars/issues/3?email_source=notifications\u0026email_token=ANM2CXKILVRS46VQ7A6HVCTQNGWPRA5CNFSM4I5ZE3E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAOFNWA#issuecomment-538728152",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ricott** [comment]
The Volvo On Call API is based on basic authentication, https://en.wikipedia.org/wiki/Basic_access_authentication. If you trace the communication you would see the base64 encoded user and password data in an HTTP header field called Authorization. As Wikipedia page says "... no confidentiality protection for the transmitted credentials. They are merely encoded with Base64 in transit, but not encrypted or hashed in any way. Therefore, Basic Authentication is typically used in conjunction with HTTPS to provide confidentiality."
This is the case here, HTTPS protocol is always used which results in encrypted communication end to end and nothing is transferred in plain text.

**Comment by babel91** [comment]
// Device DATA

let devices = await Homey.devices.getDevices();

Object.values(devices).forEach(device => {
console.log(device.name + " Id: " + device.id);
});

console.log('***');


UsedDev = ('Put device id here');



FullDev = await Homey.devices.getDevice ({id:UsedDev});

var DevArray1 = (Object.values(FullDev));

var DevArray2 = (Object.values(DevArray1[14]));

var DevArray3 = (Object.values(DevArray2[0]));

var DevTemp = (DevArray3[0]);


DevArray1.find(function(value, index) {
console.log('Visited index ', index, ' with value ', value);
});

console.log('***');

var do_tell_Array = (DevArray3[5] + ' ' + DevArray1[6] + ' ' + DevArray3[0]+ '
' + DevArray3[7]);



console.log(do_tell_Array);

return false

// Put in the device id of your volvo and run this script, in the bottom of
the console i found my id and password.


Den sön 6 okt. 2019 kl 13:21 skrev ricott <notifications@github.com>:

**Comment by ricott** [comment]
So let me try and again describe what I'm guessing your concern is :)

Your concern is that within the app settings the username and password are stored in cleartext. Something that is possible to access after you have authenticated to your Homey from your local network and use CLI to deploy code to it?

I have used the template suggested by Athom for storing app settings, https://apps.developer.athom.com/tutorial-Drivers-Pairing-System%20Views-Credentials%20Login.html. With that said I of course, want to provide an app that is as secure as possible. Ideally Homey shouldn't allow one app to read another app's settings, they should have separate namespaces. (Assuming this is the problem you are highlighting) 

I'm not sure how we can find a key to use for encrypt/decrypt that won't be accessible when you deploy another app on your Homey?

**Comment by babel91** [comment]
Exactly, but with your explenation im not sure if this really is a problem, because the network and the homey is encrypted in it self? Btw thank you for awsome respons time!Skickat från min Samsung Galaxy-smartphone.
-------- Originalmeddelande --------Från: ricott <notifications@github.com> Datum: 2019-10-06  22:03  (GMT+01:00) Till: "ricott/homey-com.volvocars" <homey-com.volvocars@noreply.github.com> Kopia: babel91 <M.adolfsson91@gmail.com>, Author <author@noreply.github.com> Ämne: Re: [ricott/homey-com.volvocars] Password/User (#3) So let me try and again describe what I'm guessing your concern is :)
Your concern is that within the app settings the username and password are stored in cleartext. Something that is possible to access after you have authenticated to your Homey from your local network and use CLI to deploy code to it?
I have used the template suggested by Athom for storing app settings, https://apps.developer.athom.com/tutorial-Drivers-Pairing-System%20Views-Credentials%20Login.html. With that said I of course, want to provide an app that is as secure as possible. Ideally Homey shouldn't allow one app to read another app's settings, they should have separate namespaces. (Assuming this is the problem you are highlighting)
I'm not sure how we can find a key to use for encrypt/decrypt that won't be accessible when you deploy another app on your Homey?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ricott/homey-com.volvocars/issues/3?email_source=notifications\u0026email_token=ANM2CXM3COCLIPSDHGAPNQ3QNJABRA5CNFSM4I5ZE3E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAOSXFY#issuecomment-538782615",
"url": "https://github.com/ricott/homey-com.volvocars/issues/3?email_source=notifications\u0026email_token=ANM2CXM3COCLIPSDHGAPNQ3QNJABRA5CNFSM4I5ZE3E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAOSXFY#issuecomment-538782615",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ricott** [comment]
I'd rather store it encrypted if it makes sense and is possible. Checking in the developer slack channel if someone is doing this.

**Comment by babel91** [comment]
Sounds good to me! I will do some reserch to, and let you know if i find
something usefull!

Den sön 6 okt. 2019 22:33ricott <notifications@github.com> skrev:

**Comment by ricott** [comment]
Solution implemented using encryption key stored in an environment variable, which is not accessible in GitHub or through the Homey API. The feature comes in version 1.0.3 which will be released after Athom approves it (usually in a few days).

**Comment by babel91** [comment]
Sounds like a good solution!Btw, the fastest answers and solution ever :D Skickat från min Samsung Galaxy-smartphone.
-------- Originalmeddelande --------Från: ricott <notifications@github.com> Datum: 2019-10-07  14:59  (GMT+01:00) Till: "ricott/homey-com.volvocars" <homey-com.volvocars@noreply.github.com> Kopia: babel91 <M.adolfsson91@gmail.com>, Author <author@noreply.github.com> Ämne: Re: [ricott/homey-com.volvocars] Password/User (#3) Solution implemented using encryption key stored in an environment variable, which is not accessible in GitHub or through the Homey API. The feature comes in version 1.0.3 which will be released after Athom approves it (usually in a few days).

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ricott/homey-com.volvocars/issues/3?email_source=notifications\u0026email_token=ANM2CXJARYDM2JCV2YHAWPLQNMXENA5CNFSM4I5ZE3E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAQHMZQ#issuecomment-538998374",
"url": "https://github.com/ricott/homey-com.volvocars/issues/3?email_source=notifications\u0026email_token=ANM2CXJARYDM2JCV2YHAWPLQNMXENA5CNFSM4I5ZE3E2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEAQHMZQ#issuecomment-538998374",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by babel91** [comment]
> So, the issue is volvos programming?

**Comment by ricott** [comment]
Now the release is out, please let me know what you see using your script

**Comment by babel91** [comment]
I used my script again, sorry for long delay, have been working a long way from home,
But the username and password is still stored without encryption.

**Comment by ricott** [comment]
Sorry for the long turnaround time, I was on vacation.
I finally managed to reproduce the problem and it seems we weren't looking at the same place. You found email and password as part of the data object associated with the device. I was under the impression they were only temporarily stored there since I wipe them later and store them at another place. When I now managed to find what you found then I checked it up and it turns out the data object is immutable (not possible to change) as per Homey's documentation. So me unsetting them didn't help obviously.

I have now new code in place that doesn't pass the credentials from the driver to the device using the data object but instead another object that is possible to wipe later. The downside is that you need to remove the device and add it again for this to happen. Since the data object is immutable it is not possible to change at all for current devices. Will issue a new minor release in coming days.
