### ISSUE TITLE
Battery status. Not working 

### ISSUE THREAD

**Issue by martin072** [ricott/homey-com.volvocars#31]
Hi. Can it be there is an issue with the battery information? I have a XC60 Hybrid model 2023

the app seems to work fine, and shows most of the info but it does not show the battery level. See screenshot 
![IMG_9577](https://github.com/ricott/homey-com.volvocars/assets/24524506/f35daddb-9ce9-441c-b4e3-7c649920be50)

**Comment by Scerulo** [comment]
Same issue

**Comment by ricott** [comment]
Since the ticket is very old I wonder if this is still a problem?
The cars supported by the Energy API are listed [here](https://developer.volvocars.com/apis/energy/v1/overview/#availability).

**Comment by martin072** [comment]
Sorry for the late reaction. Yes seems to work fine now. Thanks.
