### ISSUE TITLE
Battery level and estimate distance dont work anymore aaos23

### ISSUE THREAD

**Issue by jlfreelance** [ricott/homey-com.volvocars#32]

**Comment by ricott** [comment]
Since the ticket is very old I wonder if this is still a problem?
The cars supported by the Energy API are listed [here](https://developer.volvocars.com/apis/energy/v1/overview/#availability).

**Comment by jlfreelance** [comment]
Working nog. Thanks

Den fre 4 okt. 2024 20:22Richard Barkestam ***@***.***> skrev:

**Comment by jlfreelance** [comment]
This is working now
