### ISSUE TITLE
Volvo EX30

### ISSUE THREAD

**Issue by STD078** [ricott/homey-com.volvocars#36]
Is it possible to make the app work with the Volvo EX30?

**Comment by ricott** [comment]
Give the [test version](https://homey.app/a/com.volvocars/test/) a go, and use the connected `vehicle device` type.

**Comment by STD078** [comment]
We managed to add the car! In a test flow I now receive a notification when the car arrives home. but giving commands to the car doesn't work. I cannot start the heating or open the doors from Homey.

**Comment by ricott** [comment]
Can you include the error you get? On the settings of the device in Homey there is a debug field with the last api error.
I suspect there is no API for the EX cars as of yet, looking at the supported cars [here](https://developer.volvocars.com/apis/connected-vehicle/v2/overview/#availability).

**Comment by STD078** [comment]
[cid:storage_emulated_0_Android_data_com_samsung_android_email_provider_files__EmailTempImage_-1512234344_1728066457738_459537_jpeg_1728066457826]

[cid:storage_emulated_0_Android_data_com_samsung_android_email_provider_files__EmailTempImage_-1973803817_1728066595899_239696_jpeg_1728066595996]

Verzonden vanaf mijn Galaxy



-------- Oorspronkelijk bericht --------
Van: Richard Barkestam ***@***.***>
Datum: 04-10-2024 20:20 (GMT+01:00)
Aan: "ricott/homey-com.volvocars" ***@***.***>
Cc: STD078 ***@***.***>, Author ***@***.***>
Onderwerp: Re: [ricott/homey-com.volvocars] Volvo EX30 (Issue #36)


Can you include the error you get? On the settings of the device in Homey there is a debug field with the last api error.
I suspect there is no API for the EX cars as of yet, looking at the supported cars here<https://developer.volvocars.com/apis/connected-vehicle/v2/overview/#availability>.

**Comment by ricott** [comment]
Sorry, github haven't solved the problem of picking up images from and email - you have to add the images using their web UI.

**Comment by STD078** [comment]
![Screenshot_20241004_202950_Homey](https://github.com/user-attachments/assets/9c8ab429-ae72-4086-85e2-7e062e8d74db)
![Screenshot_20241004_202627_Homey](https://github.com/user-attachments/assets/7c953a45-fccb-4ada-8f63-f882200cb4f8)

**Comment by ricott** [comment]
So we get an internal server error at Volvo's API 😅
If you had added the car before upgrading to this test version you should remove it and re-add it. There was a problem earlier since the EX cars have fuelType set to NONE, it didn't pass as an electric car.

**Comment by STD078** [comment]
I have added the car before upgrading.
Now i can not add the car any more.
![Screenshot_20241004_204738_Homey](https://github.com/user-attachments/assets/0b7d7cef-9653-46b4-81c5-23c93ced83a5)

**Comment by ricott** [comment]
You need to remove the old device first, but maybe you did that?
Have a user in the forum thread which added his EX30 using the test version the other day

**Comment by STD078** [comment]
I did remove the car first.
Now also tried removing and reinstalling the app.
No car can be found.



Verzonden vanaf mijn Galaxy


-------- Oorspronkelijk bericht --------
Van: Richard Barkestam ***@***.***>
Datum: 04-10-2024 20:54 (GMT+01:00)
Aan: "ricott/homey-com.volvocars" ***@***.***>
Cc: STD078 ***@***.***>, Author ***@***.***>
Onderwerp: Re: [ricott/homey-com.volvocars] Volvo EX30 (Issue #36)


You need to remove the old device first, but maybe you did that?
Have a user in the forum thread which added his EX30 using the test version the other day

**Comment by STD078** [comment]
Also tried the normal app wich i added the car in before.  Also no succes.

**Comment by STD078** [comment]
Also tried another Homey.
Nu succes.

**Comment by ricott** [comment]
Maybe you can try the endpoint from the volvo developer portal?
This is the endpoint used to list vehicles on the account, for the `connected vehicle` device type.
https://developer.volvocars.com/apis/connected-vehicle/v2/endpoints/vehicle/#list-vehicles

**Comment by STD078** [comment]
I have no idea how to do this.  I'll try to find out! Thank you

**Comment by STD078** [comment]
Unfortunaly i can't figure out what to do. Some help would be much appriciated!

**Comment by STD078** [comment]
problem solved. app works great
