### ISSUE TITLE
No battery status anymore on V60 PHEV 2021

### ISSUE THREAD

**Issue by pkaak** [ricott/homey-com.volvocars#37]
For some reasons Homey does not show battery information anymore of my PHEV on Volvo On Call
The json that the app gets shows battery info.
This results in my flows not working anymore as I do not have the card anymore for 'If Battery Level Changed' stopping my flows that inform me when the battery is fully charged. 

Seems to be a problem of the Homey App as Home Assistance still gets this information from Volvo.

Attached is the debug json on the attributes VOC status/attributes the app shows coming from my account (obfuscating some information). 

App version 1.3.2
Homey version 8.1.3 (on Homey Early 2019)
Edit: just updated to Homey version 12.1.0 but problem still exists

[volvooncall api v60 phev.txt](https://github.com/user-attachments/files/17297465/volvooncall.api.v60.phev.txt)
![volvo1](https://github.com/user-attachments/assets/eb35cf64-b8a0-4ff4-8e27-125f99eaf915)
![volvo3](https://github.com/user-attachments/assets/3d99f0ed-2984-4f3c-9e83-e04638b879ce)
![volvo2](https://github.com/user-attachments/assets/874d0023-41b6-4226-92d7-05084d5a6100)

**Comment by ricott** [comment]
Which device type are you using?
`Volvo on call` or `Connected vehicle`?

**Comment by pkaak** [comment]
Github insert the json file as a link in my original message.  I've attached it here again:
[volvooncall.api.v60.phev.txt](https://github.com/user-attachments/files/17305741/volvooncall.api.v60.phev.txt)

I am using Volvo On Call.

**Comment by ricott** [comment]
There is a setting on the device named `PHEV` which should have a `true` or `false` value - what do you have there?
I have a V60, 2021, hybrid as the only test car in my Homey and for that model I do get battery stats.

**Comment by ricott** [comment]
There is a new [test version](https://homey.app/a/com.volvocars/test/).
Hard to diagnose since it works here, but I have added logic to re-add the capabilities if they are missing. If you restart the app they should appear again (I hope)
