### ISSUE TITLE
car not "connected" anymore

### ISSUE THREAD

**Issue by Rligtenberg** [ricott/homey-com.volvocars#38]
since last week I am unable to access my car through the homey devices anymore. I get the "red notification light". Already tried re-connecting by creating a new API and attempting to log in using my credentials multiple times. I get the following error;

Error: Login failed! Call '/as/token.oauth2' failed, HTTP status code '400', and message '{ error: 'unauthorized_client' }'

Previously it worked and I'm sure I'm using the correct credentials... Any ideas?

**Comment by ricott** [comment]
Don't see the problem on my end, but would be interesting to know the model and year of your car.

**Comment by ricott** [comment]
I see the HA plugin has added support for OTP - something you have enabled on your Volvo account?

**Comment by hhuibers** [comment]
I have the same problem, it was working good until last week.
I'm sure I'm using the correct credentials.
Regenerated new VCC API Keys, but that does not work.

I have a XC40 EV model year 2023

**Comment by Rligtenberg** [comment]
Model V60 my2023. @ricott Not sure what you meen by OTP

**Comment by ricott** [comment]
Sorry for the tech lingo, OTP = one time password. If you login [here](https://volvoid.eu.volvocars.com/Account/), button top right corner. Will Volvo send you an email with a verification code to enter before you are logged in?

**Comment by hhuibers** [comment]
i have test this via the shared link and i can login without OTP

**Comment by Rligtenberg** [comment]
I did get a text message with verification code using the link and my login credentials

**Comment by hhuibers** [comment]
i have test it again and clicking manually logoff by all active sessions and login again.
After that i'm also get a text message with verification code using the link and my login credentials

do you think that possibly OTP is the cause of the error we are getting from the homey app? If Yes then probarly the homey app needs a update to deal with OTP, or what do you think?

**Comment by ricott** [comment]
I think we need to add support for OTP (somehow)...

**Comment by hhuibers** [comment]
@ricott does it help when i run diagnostics  and send to you from the volvo on call app in homey?

**Comment by ricott** [comment]
https://community.homey.app/t/app-pro-volvo-on-call-connected-technology-that-makes-your-life-easier/20828/187?u=richard_b

**Comment by Marsy0502** [comment]
I have also the same problem.
It was working good until 17-10-2024.
I'm using the correct credentials.
Also regenerated new VCC API Keys, but it still does not work.
My Volvo is a C40 model year 2022

**Comment by ricott** [comment]
Please read the forum thread I linked above. The new test version is confirmed to solve the problem

**Comment by Marsy0502** [comment]
Hi Richard. You solved my problem with test version.
Many thx

**Comment by ricott** [comment]
Test version published, but needs approval from Athom which may take a couple of days

**Comment by Rligtenberg** [comment]
Solves my problem, tnx!
