### ISSUE TITLE
Incompatible homey 

### ISSUE THREAD

**Issue by mortenkols** [ricott/homey-com.volvocars#4]
![30474743-7282-4251-A74D-83CE4C3216A0](https://user-images.githubusercontent.com/32611195/67699304-404d2700-f9ac-11e9-9716-56f543596816.png)

Why cant i download this app?

**Comment by ricott** [comment]
In the last release I raised the app compatibility setting to Homey v3.0. It adds some new functionality that I use in the app. V3 should be released in the coming days. After you upgrade you will be able to install the app.

**Comment by ricott** [comment]
Homey v3 is out since a few days so I assume this is no longer a problem.
