### ISSUE TITLE
54554b7f-a6d1-4d1b-9ccb-989512d86879

### ISSUE THREAD

**Issue by YoKingy** [ricott/homey-com.volvocars#41]
Hoe kom ik aan een keyboard voor volvo connect om deze te proberen?
Hoe kan ik een oude volvo geheel wissen.  Waarom werkt een nieuwe volvo niet met homey. Krijg geen foutmelding maar wordt ook niet geïnstalleerd.

**Comment by ricott** [comment]
English please 😅

**Comment by YoKingy** [comment]
Who can provide more clarity on installing volvo on call with the connected version.
You need to fill in a VCC_API of 32 characters for this, which you have to get somewhere on the Volvo develop site!!! Then the search begins WHERE somewhere you can do a try out but it doesn't work in Homey somewhere you can fill in your volvo details and a veeeeery long API code appears.
in other words I don't understand it anymore while the old volvo could be installed like this. Who has a solution?
