### ISSUE TITLE
App is not working

### ISSUE THREAD

**Issue by np1957** [ricott/homey-com.volvocars#9]
Hi I have succeeded to connect my Car to the app via Volvo On call Login credentials but the status of the parameters does not got updated. When I leave home or come home the status does not get updated. The other data does not get updated either. I want to use the Car information when I reach home to create a flow to open the garage door.

**Comment by np1957** [comment]
Hi, Thanks for guidning of the settings. All settings as you Proposed are Correct. Still i cannot get the position updated. Is there any other solition to get this work?
Thanks in advance.
Kind Regards Nitin


![E4513DE5-17AB-4FB1-9B3D-0136FDA2791F](https://user-images.githubusercontent.com/70093550/91088068-badce680-e651-11ea-8117-a47889c15131.jpeg)
![8CBD705D-97AD-4CB6-8808-E40E1081FC5B](https://user-images.githubusercontent.com/70093550/91088070-bb757d00-e651-11ea-8975-0c83e5adb137.jpeg)

**Comment by ricott** [comment]
Is the problem still there?
Otherwise, the only thing I can think of is to add a new debug field with geo coordinates that the VOC API returns.

**Comment by ricott** [comment]
v1.1.3, to be approved by Athom, contains a debug setting for last positon data from VOC API
